### PR TITLE
Remove code generation

### LINKED ISSUE #31: Module depends on implementation details and has packaging issues
This module's build process does some crazy and completely unnecessary things. E.g. it will only work when installed to the site repository:
https://github.com/hoelzro/p6-linenoise/blob/76f4b2dbbb8ce0f516aea1e0dd1423234a69817f/fill-constants.pl#L28

It expects a `dist` subdirectory in the site repository containing a file matching the dist-id obtained from %?RESOURCES:
https://github.com/hoelzro/p6-linenoise/blob/76f4b2d/lib/Linenoise.pm6.in#L18
It then expects the aforementioned file to have a certain serialization format and a `resources` subdirectory to exist with a certain structure.
https://github.com/hoelzro/p6-linenoise/blob/76f4b2d/lib/Linenoise.pm6.in#L24
None of this is guaranteed! This is going to change in the near future! Furthermore there's no reason at all for this trickery. It doesn't make any sense.

Then there's this, which will prevent packaging for Linux distribution or even worse create broken packages:
https://github.com/hoelzro/p6-linenoise/blob/76f4b2d/lib/Linenoise.pm6.in#L25
Why is there a call to `.Str` there? This will break when the module gets installed through the Staging repository as the path will change between compilation and runtime. It will also cause linter check failures as suddenly a build directory path is found in the precomp files.

Why does the distro even generate Perl 6 code at build time? There's no reason for that either. That's just a huge complication that will make it much harder for our ecosystem tools.

### PR DESCRIPTION
**Pull request by ugexe**
Previously a module template was filled in with build-time generated
values. This adds some C helper functions to generate these values,
and removes the templated module in favor of these new helpers inside
the (now) non-template module.

Resolves #31 #33

### CODE REVIEW

**Comment by ugexe** [comment]
ping @niner

**Review by JJ — CHANGES_REQUESTED** [review]
This looks fine, and it's great work. But I would really like to see a test for it.

**Comment by niner** [comment]
Beautiful :)

**Comment by ugexe** [comment]
Well now there are merge conflicts. This is ridiculous. Fix it yourself.

**Comment by JJ** [comment]
@ugexe, it's not very helpful to remove the repository. It really makes the task to fix this really difficult. I would please ask you to reinstate it, and I'll do my best to fix it as you requested. Windows tests are already working, and I'try and get the MacOS tests up and running soon-ish.

**Comment by ugexe** [comment]
The ci "test" installs rakudo-star,  which itself installs Linenoise (among other things)... so I just don't have trust in this module anymore and will stick with Readline. Thanks.

**Comment by JJ** [comment]
Hi

El jue., 28 nov. 2019 a las 20:22, Nick Logan (<notifications@github.com>)
escribió:

> The ci "test" installs rakudo-star, which itself installs Linenoise (among
> other things)... so I just don't have trust in this module anymore and will
> stick with Readline. Thanks.
>
>
There's no Windows distribution that does not include Linenoise. Even so,
and as you probably know, zef test . tests only the local version. Quite
clearly, if you follow the CI steps, everything is compiled on the same
file. I don't think installed version of Linenoise pollutes in any way
local tests; upstream dependencies like LibraryMake might, but then, It's
not related to this module.

**Comment by ugexe** [comment]
JJ ok. I will still prefer Readline in the future. Thanks.

**Comment by JJ** [comment]
I would still appreciate if you reinstated the code you have removed so
that we can use it. Now there are tests for all platforms it's going to be
easier to automatically check for errors. If you don't want to change it,
that's fine, but as I said it's a good piece of work and it would really
help this.

**Comment by ugexe** [comment]
I'm only going to ask you once: stop contacting me. Thank you.

**Pull request closed without merging**
